### ISSUE TITLE
docker模式运行后，接口返回404

### ISSUE THREAD

**Issue by reluo** [akfamily/aktools#114]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/24249261/202345184-fa36f602-8881-401c-aa13-3d918f8f35cf.png">
如图所示：docker模式运行后，接口返回404

**Comment by Geek-Kevin2333** [comment]
同问，我也遇到了这个问题，请问楼主解决了吗

**Comment by jindaxiang** [comment]
> <img alt="image" width="655" src="https://user-images.githubusercontent.com/24249261/202345184-fa36f602-8881-401c-aa13-3d918f8f35cf.png">
> 
> 如图所示：docker模式运行后，接口返回404

本地测试可以正常使用；建议查看下 AKShare 的版本
