### ISSUE TITLE
/usr/bin/python: No module named aktools.__main__; 'aktools' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by liuenci** [akfamily/aktools#116]
环境：python3.6

运行命令：python -m aktools，报下面的错误
/usr/bin/python: No module named aktools.__main__; 'aktools' is a package and cannot be directly executed

**Comment by jindaxiang** [comment]
> 环境：python3.6
> 
> 运行命令：python -m aktools，报下面的错误 /usr/bin/python: No module named aktools.**main**; 'aktools' is a package and cannot be directly executed

Python 3.7 及以上版本
