### ISSUE TITLE
404错误

### ISSUE THREAD

**Issue by Geek-Kevin2333** [akfamily/aktools#117]
使用docker模式在云服务器上运行后，无论是在云服务器上请求127.0.0.1或者0.0.0.0+对应端口还是向云服务器发请求，利用docker进行路由转发，都报404错误，如图所示
![image](https://user-images.githubusercontent.com/80016929/209419082-0a8ca5d6-f314-42b8-b8f0-e5dc19bf3f20.png)

**Comment by jindaxiang** [comment]
> 使用docker模式在云服务器上运行后，无论是在云服务器上请求127.0.0.1或者0.0.0.0+对应端口还是向云服务器发请求，利用docker进行路由转发，都报404错误，如图所示 ![image](https://user-images.githubusercontent.com/80016929/209419082-0a8ca5d6-f314-42b8-b8f0-e5dc19bf3f20.png)

建议查看下 AKShare 的版本
