### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by The-timing** [akfamily/aktools#121]
![image](https://user-images.githubusercontent.com/48267506/215271901-ca617318-08e5-44b9-85c1-fb5ec46dd9fe.png)
![image](https://user-images.githubusercontent.com/48267506/215271939-99403ba2-a5c8-4634-8f35-7eb51d8f3deb.png)
提示文件未找到

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/48267506/215271901-ca617318-08e5-44b9-85c1-fb5ec46dd9fe.png) ![image](https://user-images.githubusercontent.com/48267506/215271939-99403ba2-a5c8-4634-8f35-7eb51d8f3deb.png) 提示文件未找到

本地测试可以正常安装使用；请检查本地环境配置
