### ISSUE TITLE
 AttributeError: module 'click.utils' has no attribute ._expand_args.  i was able to set up server using 'python -m aktools'. but i cant now.

### ISSUE THREAD

**Issue by tyePhDCandy** [akfamily/aktools#124]
# i updated my aktools to latest version. and run these code to set up server.
```python
python -m aktools
```

# error messages
```log
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\runpy.py:197 in            │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   194 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   195 │   if alter_argv:                                                                         │
│   196 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 197 │   return _run_code(code, main_globals, None,                                             │
│   198 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   199                                                                                            │
│   200 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = True                                                                          │ │
│ │         code = <code object <module> at 0x000002972A1E5C90, file                             │ │
│ │                "C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-… │ │
│ │                line 3>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': '\nDate: 2022/9/27 19:05\nDesc: CLI 执行入口文件\n运行 `pytho… │ │
│ │                -m aktools` 相当于运行 `python -m '+21,                                       │ │
│ │                │   '__package__': 'aktools',                                                 │ │
│ │                │   '__loader__': <_frozen_importlib_external.SourceFileLoader object at      │ │
│ │                0x0000029729AAD160>,                                                          │ │
│ │                │   '__spec__': ModuleSpec(name='aktools.__main__',                           │ │
│ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
│ │                0x0000029729AAD160>,                                                          │ │
│ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │                │   'cli': <module 'aktools.cli' from                                         │ │
│ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = 'aktools.__main__'                                                            │ │
│ │     mod_spec = ModuleSpec(name='aktools.__main__',                                           │ │
│ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
│ │                0x0000029729AAD160>,                                                          │ │
│ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\runpy.py:87 in _run_code   │
│                                                                                                  │
│    84 │   │   │   │   │      __loader__ = loader,                                                │
│    85 │   │   │   │   │      __package__ = pkg_name,                                             │
│    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  87 │   exec(code, run_globals)                                                                │
│    88 │   return run_globals                                                                     │
│    89                                                                                            │
│    90 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │         code = <code object <module> at 0x000002972A1E5C90, file                             │ │
│ │                "C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-… │ │
│ │                line 3>                                                                       │ │
│ │        fname = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <_frozen_importlib_external.SourceFileLoader object at 0x0000029729AAD160>    │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='aktools.__main__',                                           │ │
│ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
│ │                0x0000029729AAD160>,                                                          │ │
│ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
│ │     pkg_name = 'aktools'                                                                     │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': '\nDate: 2022/9/27 19:05\nDesc: CLI 执行入口文件\n运行 `pytho… │ │
│ │                -m aktools` 相当于运行 `python -m '+21,                                       │ │
│ │                │   '__package__': 'aktools',                                                 │ │
│ │                │   '__loader__': <_frozen_importlib_external.SourceFileLoader object at      │ │
│ │                0x0000029729AAD160>,                                                          │ │
│ │                │   '__spec__': ModuleSpec(name='aktools.__main__',                           │ │
│ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
│ │                0x0000029729AAD160>,                                                          │ │
│ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │                │   'cli': <module 'aktools.cli' from                                         │ │
│ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\aktools\__ma │
│ in__.py:16 in <module>                                                                           │
│                                                                                                  │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│ ❱ 16 │   main()                                                                                  │
│   17                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ __annotations__ = {}                                                                         │ │
│ │    __builtins__ = <module 'builtins' (built-in)>                                             │ │
│ │      __cached__ = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9… │ │
│ │         __doc__ = '\nDate: 2022/9/27 19:05\nDesc: CLI 执行入口文件\n运行 `python -m aktools… │ │
│ │                   相当于运行 `python -m '+21                                                 │ │
│ │        __file__ = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9… │ │
│ │      __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x0000029729AAD160> │ │
│ │        __name__ = '__main__'                                                                 │ │
│ │     __package__ = 'aktools'                                                                  │ │
│ │        __spec__ = ModuleSpec(name='aktools.__main__',                                        │ │
│ │                   loader=<_frozen_importlib_external.SourceFileLoader object at              │ │
│ │                   0x0000029729AAD160>,                                                       │ │
│ │                   origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versio… │ │
│ │       __title__ = 'AKTools'                                                                  │ │
│ │             cli = <module 'aktools.cli' from                                                 │ │
│ │                   'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9… │ │
│ │            main = <function main at 0x0000029729A6FF70>                                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\aktools\__ma │
│ in__.py:12 in main                                                                               │
│                                                                                                  │
│    9                                                                                             │
│   10                                                                                             │
│   11 def main():                                                                                 │
│ ❱ 12 │   cli.app(prog_name=__title__)                                                            │
│   13                                                                                             │
│   14                                                                                             │
│   15 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\main.p │
│ y:328 in __call__                                                                                │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\main.p │
│ y:311 in __call__                                                                                │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\click\core.p │
│ y:829 in __call__                                                                                │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\core.p │
│ y:716 in main                                                                                    │
│                                                                                                  │
│ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\core.p │
│ y:190 in _main                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'click.utils' has no attribute '_expand_args'
```

**Comment by jindaxiang** [comment]
> # i updated my aktools to latest version. and run these code to set up server.
> ```python
> python -m aktools
> ```
> 
> # error messages
> ```
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\runpy.py:197 in            │
> │ _run_module_as_main                                                                              │
> │                                                                                                  │
> │   194 │   main_globals = sys.modules["__main__"].__dict__                                        │
> │   195 │   if alter_argv:                                                                         │
> │   196 │   │   sys.argv[0] = mod_spec.origin                                                      │
> │ ❱ 197 │   return _run_code(code, main_globals, None,                                             │
> │   198 │   │   │   │   │    "__main__", mod_spec)                                                 │
> │   199                                                                                            │
> │   200 def run_module(mod_name, init_globals=None,                                                │
> │                                                                                                  │
> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
> │ │   alter_argv = True                                                                          │ │
> │ │         code = <code object <module> at 0x000002972A1E5C90, file                             │ │
> │ │                "C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-… │ │
> │ │                line 3>                                                                       │ │
> │ │ main_globals = {                                                                             │ │
> │ │                │   '__name__': '__main__',                                                   │ │
> │ │                │   '__doc__': '\nDate: 2022/9/27 19:05\nDesc: CLI 执行入口文件\n运行 `pytho… │ │
> │ │                -m aktools` 相当于运行 `python -m '+21,                                       │ │
> │ │                │   '__package__': 'aktools',                                                 │ │
> │ │                │   '__loader__': <_frozen_importlib_external.SourceFileLoader object at      │ │
> │ │                0x0000029729AAD160>,                                                          │ │
> │ │                │   '__spec__': ModuleSpec(name='aktools.__main__',                           │ │
> │ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
> │ │                0x0000029729AAD160>,                                                          │ │
> │ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
> │ │                │   '__annotations__': {},                                                    │ │
> │ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
> │ │                │   '__file__':                                                               │ │
> │ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │                │   '__cached__':                                                             │ │
> │ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │                │   'cli': <module 'aktools.cli' from                                         │ │
> │ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │                │   ... +2                                                                    │ │
> │ │                }                                                                             │ │
> │ │     mod_name = 'aktools.__main__'                                                            │ │
> │ │     mod_spec = ModuleSpec(name='aktools.__main__',                                           │ │
> │ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
> │ │                0x0000029729AAD160>,                                                          │ │
> │ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
> │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\runpy.py:87 in _run_code   │
> │                                                                                                  │
> │    84 │   │   │   │   │      __loader__ = loader,                                                │
> │    85 │   │   │   │   │      __package__ = pkg_name,                                             │
> │    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
> │ ❱  87 │   exec(code, run_globals)                                                                │
> │    88 │   return run_globals                                                                     │
> │    89                                                                                            │
> │    90 def _run_module_code(code, init_globals=None,                                              │
> │                                                                                                  │
> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
> │ │       cached = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │         code = <code object <module> at 0x000002972A1E5C90, file                             │ │
> │ │                "C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-… │ │
> │ │                line 3>                                                                       │ │
> │ │        fname = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │ init_globals = None                                                                          │ │
> │ │       loader = <_frozen_importlib_external.SourceFileLoader object at 0x0000029729AAD160>    │ │
> │ │     mod_name = '__main__'                                                                    │ │
> │ │     mod_spec = ModuleSpec(name='aktools.__main__',                                           │ │
> │ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
> │ │                0x0000029729AAD160>,                                                          │ │
> │ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
> │ │     pkg_name = 'aktools'                                                                     │ │
> │ │  run_globals = {                                                                             │ │
> │ │                │   '__name__': '__main__',                                                   │ │
> │ │                │   '__doc__': '\nDate: 2022/9/27 19:05\nDesc: CLI 执行入口文件\n运行 `pytho… │ │
> │ │                -m aktools` 相当于运行 `python -m '+21,                                       │ │
> │ │                │   '__package__': 'aktools',                                                 │ │
> │ │                │   '__loader__': <_frozen_importlib_external.SourceFileLoader object at      │ │
> │ │                0x0000029729AAD160>,                                                          │ │
> │ │                │   '__spec__': ModuleSpec(name='aktools.__main__',                           │ │
> │ │                loader=<_frozen_importlib_external.SourceFileLoader object at                 │ │
> │ │                0x0000029729AAD160>,                                                          │ │
> │ │                origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\… │ │
> │ │                │   '__annotations__': {},                                                    │ │
> │ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
> │ │                │   '__file__':                                                               │ │
> │ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │                │   '__cached__':                                                             │ │
> │ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │                │   'cli': <module 'aktools.cli' from                                         │ │
> │ │                'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9.7\… │ │
> │ │                │   ... +2                                                                    │ │
> │ │                }                                                                             │ │
> │ │  script_name = None                                                                          │ │
> │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\aktools\__ma │
> │ in__.py:16 in <module>                                                                           │
> │                                                                                                  │
> │   13                                                                                             │
> │   14                                                                                             │
> │   15 if __name__ == "__main__":                                                                  │
> │ ❱ 16 │   main()                                                                                  │
> │   17                                                                                             │
> │                                                                                                  │
> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
> │ │ __annotations__ = {}                                                                         │ │
> │ │    __builtins__ = <module 'builtins' (built-in)>                                             │ │
> │ │      __cached__ = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9… │ │
> │ │         __doc__ = '\nDate: 2022/9/27 19:05\nDesc: CLI 执行入口文件\n运行 `python -m aktools… │ │
> │ │                   相当于运行 `python -m '+21                                                 │ │
> │ │        __file__ = 'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9… │ │
> │ │      __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x0000029729AAD160> │ │
> │ │        __name__ = '__main__'                                                                 │ │
> │ │     __package__ = 'aktools'                                                                  │ │
> │ │        __spec__ = ModuleSpec(name='aktools.__main__',                                        │ │
> │ │                   loader=<_frozen_importlib_external.SourceFileLoader object at              │ │
> │ │                   0x0000029729AAD160>,                                                       │ │
> │ │                   origin='C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versio… │ │
> │ │       __title__ = 'AKTools'                                                                  │ │
> │ │             cli = <module 'aktools.cli' from                                                 │ │
> │ │                   'C:\\Users\\tyehuo\\scoop\\apps\\pyenv\\current\\pyenv-win\\versions\\3.9… │ │
> │ │            main = <function main at 0x0000029729A6FF70>                                      │ │
> │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\aktools\__ma │
> │ in__.py:12 in main                                                                               │
> │                                                                                                  │
> │    9                                                                                             │
> │   10                                                                                             │
> │   11 def main():                                                                                 │
> │ ❱ 12 │   cli.app(prog_name=__title__)                                                            │
> │   13                                                                                             │
> │   14                                                                                             │
> │   15 if __name__ == "__main__":                                                                  │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\main.p │
> │ y:328 in __call__                                                                                │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\main.p │
> │ y:311 in __call__                                                                                │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\click\core.p │
> │ y:829 in __call__                                                                                │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\core.p │
> │ y:716 in main                                                                                    │
> │                                                                                                  │
> │ C:\Users\tyehuo\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\lib\site-packages\typer\core.p │
> │ y:190 in _main                                                                                   │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: module 'click.utils' has no attribute '_expand_args'
> ```

我这边测试没有问题，可以创建一个虚拟环境测试下

**Comment by bobokingbao** [comment]
同样的问题，在anaconda下建立的新的虚拟环境：Python 3.8.16
aktool版本：0.0.83

**Comment by tyePhDCandy** [comment]
> 

似乎存在一些不稳定运行的情况。有的虚拟环境可以正常进行`python -m aktools`，有些不可以。
目前未发现原因。
