### ISSUE TITLE
api在接口结果无数据的情况下，会报错NoneType' object has no attribute 'to_json'

### ISSUE THREAD

**Issue by doMySelfZy** [akfamily/aktools#13]
api.py中
`temp_df = eval("ak." + item_id + f"({eval_str})").to_json(orient='records', date_format='iso')`
如果调用接口查询结果无数据，会报**'NoneType' object has no attribute 'to_json'**，
对象结果无法转成json，http返回结果**Internal Server Error**
建议加上接口返回判断，处理一下。

**Comment by jindaxiang** [comment]
> api.py中 `temp_df = eval("ak." + item_id + f"({eval_str})").to_json(orient='records', date_format='iso')` 如果调用接口查询结果无数据，会报**'NoneType' object has no attribute 'to_json'**， 对象结果无法转成json，http返回结果**Internal Server Error** 建议加上接口返回判断，处理一下。

具体哪个接口，方便说下吗？我复现下

**Comment by jindaxiang** [comment]
> api.py中 `temp_df = eval("ak." + item_id + f"({eval_str})").to_json(orient='records', date_format='iso')` 如果调用接口查询结果无数据，会报**'NoneType' object has no attribute 'to_json'**， 对象结果无法转成json，http返回结果**Internal Server Error** 建议加上接口返回判断，处理一下。

已修复，升级 AKTools 到 0.0.34 版本使用
