### ISSUE TITLE
Can't use aktools-0.0.83 with python 3.8.10 on mac 64 ( akshare-1.9.97)

### ISSUE THREAD

**Issue by matthewxuda** [akfamily/aktools#132]
P_D-MB0:Desktop xan$ python3 -m aktools
请访问：http://127.0.0.1:8080/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools
当前的 AKTools 版本为：0.0.83，AKShare 版本为：1.9.97
点击打开 HTTP API 主页：http://127.0.0.1:8080/
点击打开接口导览：http://127.0.0.1:8080/docs
/usr/bin/python: No module named uvicorn
P_D-MB0:Desktop xan$ lsof -i:8080
P_D-MB0:Desktop xan:Desktop xianxian$ 

open http://127.0.0.1:8080/version, show:
无法访问此网站127.0.0.1 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by jindaxiang** [comment]
> P_D-MB0:Desktop xan$ python3 -m aktools 请访问：http://127.0.0.1:8080/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools 当前的 AKTools 版本为：0.0.83，AKShare 版本为：1.9.97 点击打开 HTTP API 主页：http://127.0.0.1:8080/ 点击打开接口导览：http://127.0.0.1:8080/docs /usr/bin/python: No module named uvicorn P_D-MB0:Desktop xan$ lsof -i:8080 P_D-MB0:Desktop xan:Desktop xianxian$
> 
> open http://127.0.0.1:8080/version, show: 无法访问此网站127.0.0.1 拒绝了我们的连接请求。 请试试以下办法：
> 
> 检查网络连接 检查代理服务器和防火墙 ERR_CONNECTION_REFUSED

可以检查下您本地的配置
