### ISSUE TITLE
访问分析师详情接口失败

### ISSUE THREAD

**Issue by sshling** [akfamily/aktools#136]
curl --location --request GET 'http://127.0.0.1:8080/api/public/stock_analyst_detail_em?analyst_id=11000277440&indicator=最新跟踪成分股'  

![Snipaste_2023-07-23_12-45-41](https://github.com/akfamily/aktools/assets/661568/c530e3d6-6a8b-4436-9d6a-0a59c09289e5)
![Snipaste_2023-07-23_12-45-41](https://github.com/akfamily/aktools/assets/661568/33c94796-5c6e-4425-84d5-f2e8437ec43f)

**Comment by albertandking** [comment]
> curl --location --request GET '[http://127.0.0.1:8080/api/public/stock_analyst_detail_em?analyst_id=11000277440&indicator=最新跟踪成分股](http://127.0.0.1:8080/api/public/stock_analyst_detail_em?analyst_id=11000277440&indicator=%E6%9C%80%E6%96%B0%E8%B7%9F%E8%B8%AA%E6%88%90%E5%88%86%E8%82%A1)'
> 
> ![Snipaste_2023-07-23_12-45-41](https://user-images.githubusercontent.com/661568/255374755-c530e3d6-6a8b-4436-9d6a-0a59c09289e5.png) ![Snipaste_2023-07-23_12-45-41](https://user-images.githubusercontent.com/661568/255374772-33c94796-5c6e-4425-84d5-f2e8437ec43f.png)

可以正常使用
