### ISSUE TITLE
ubuntu 上 python3 -m aktools 会有找不到python的错误.

### ISSUE THREAD

**Issue by percinor** [akfamily/aktools#138]
在ubuntu的vps安装aktools ,因为ubuntu中安装完成后，命令时python3  ,会返回找不到python 的错误，有什么解决的方法么？？谢谢

**Comment by albertandking** [comment]
> 在ubuntu的vps安装aktools ,因为ubuntu中安装完成后，命令时python3 ,会返回找不到python 的错误，有什么解决的方法么？？谢谢

这个应该是服务器的问题，跟本项目无关

**Comment by liujan** [comment]
/usr/local/lib/python3.11/dist-packages/aktools
   编辑cli.py文件，将
   f"python -m uviron main:app ..." 改为 f"python3 -m uviron main:app ..."  即可
