### ISSUE TITLE
使用个股新闻接口出错

### ISSUE THREAD

**Issue by oooycool** [akfamily/aktools#144]
个股新闻
接口: stock_news_em

目标地址: http://so.eastmoney.com/news/s

描述: 东方财富指定个股的新闻资讯数据

限量: 当日最近 100 条新闻资讯数据

输入参数

名称	类型	描述
symbol	str	symbol="300059"; 股票代码或其他关键词
输出参数

名称	类型	描述
关键词	object	-
新闻标题	object	-
新闻内容	object	-
发布时间	object	-
文章来源	object	-
新闻链接	object	-
接口示例

---

import akshare as ak

stock_news_em_df = ak.stock_news_em(symbol="600000")
stock_news_em_df

---
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
c:\Users\Frank\Synology\0Programing\AutoDailyReport.ipynb 单元格 21 line 2
      1 # 个股新闻
      2 # 接口: stock_news_em
      3 
   (...)
     24 
     25 # import akshare as ak
---> 27 stock_news_em_df = ak.stock_news_em(symbol="600000")
     28 stock_news_em_df
     29 # 数据示例
     30 
     31 #        关键词  ...                                               新闻链接
   (...)
     41 # 98  300059  ...  http://finance.eastmoney.com/a/202207192454107...
     42 # 99  300059  ...  http://finance.eastmoney.com/a/202206212419852...

File c:\Users\Frank\AppData\Local\Programs\Python\Python311\Lib\site-packages\akshare\news\news_stock.py:36, in stock_news_em(symbol)
     32 data_text = r.text
     33 data_json = json.loads(
     34     data_text.strip("jQuery3510875346244069884_1668256937995(")[:-1]
     35 )
---> 36 temp_df = pd.DataFrame(data_json["result"]["cmsArticleWebOld"])
     37 temp_df.rename(
     38     columns={
     39         "date": "发布时间",
   (...)
     47     inplace=True,
     48 )
     49 temp_df["关键词"] = symbol

KeyError: 'cmsArticleWebOld'

**Comment by albertandking** [comment]
> stock_news_em

目前接口正常
