### ISSUE TITLE
stock_news_em调用报错

### ISSUE THREAD

**Issue by congcong009** [akfamily/aktools#147]
stock_news_em函数在akshare的python环境下调用正常，在docker部署后，以http访问：

```shell
http://192.168.1.61:8280/api/public/stock_news_em?symbol=002771
````

报错如下：

> {
error: "请输入正确的参数错误 'cmsArticleWebOld'，请升级 AKShare 到最新版本并在文档中确认该接口的使用方式：https://www.akshare.xyz"
}

docker 中的 akshare 已经升级到最新版本，错误依旧。

**Comment by albertandking** [comment]
> stock_news_em函数在akshare的python环境下调用正常，在docker部署后，以http访问：
> 
> ```shell
> http://192.168.1.61:8280/api/public/stock_news_em?symbol=002771
> ```
> 
> 报错如下：
> 
> > {
> > error: "请输入正确的参数错误 'cmsArticleWebOld'，请升级 AKShare 到最新版本并在文档中确认该接口的使用方式：https://www.akshare.xyz"
> > }
> 
> docker 中的 akshare 已经升级到最新版本，错误依旧。

目前接口正常
