### ISSUE TITLE
docker部署，已更新akshare到最新版，调用stock_bid_ask_em返回未找到该接口

### ISSUE THREAD

**Issue by Arthaslcm** [akfamily/aktools#155]
{"error":"未找到该接口，请升级 AKShare 到最新版本并在文档中确认该接口的使用方式：https://www.akshare.xyz"}

**Comment by Arthaslcm** [comment]
访问地址：
xxx/api/public/stock_bid_ask_em?symbol=310000

调用stock_zh_a_spot_em接口是正常的

**Comment by albertandking** [comment]
> stock_bid_ask_em

目前直接接受股票代码
