### ISSUE TITLE
接口报错 api/public/futures_zh_spot 

### ISSUE THREAD

**Issue by ODomWang** [akfamily/aktools#156]
版本1.8.95
![image](https://github.com/akfamily/aktools/assets/34358342/72021a2d-5434-40cc-a0bd-acdb5a140568)

**Comment by albertandking** [comment]
> 版本1.8.95 ![image](https://private-user-images.githubusercontent.com/34358342/307274063-72021a2d-5434-40cc-a0bd-acdb5a140568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDcyMzksIm5iZiI6MTcwODg0NjkzOSwicGF0aCI6Ii8zNDM1ODM0Mi8zMDcyNzQwNjMtNzIwMjFhMmQtNTQzNC00MGNjLWEwYmQtYWNkYjVhMTQwNTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA3NDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDRjNzM4ZmY0ZDU5N2ZiN2I2MzU1Mjk0OTljNTNiZmU3ZmMxZDMxZDlkM2NiMTdjYjZlNDhlMDIyMzQ0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nP-WLbqVytDSuW5RMuFeCnsauXLNaj4SdQPjgm3t2tE)

接口测试正常，升级到最新版使用

**Comment by ODomWang** [comment]
akshare 版本1.2.78
aktools 0.0.86
pandas 2.2.1 
还有什么要更新的
