### ISSUE TITLE
Python 3.10.12 运行aktools 提示 No module named uvicorn

### ISSUE THREAD

**Issue by yuming2046** [akfamily/aktools#158]
Python 3.10.12 运行aktools 提示 No module named uvicorn，完整提示下图，这是怎么回事
<img width="566" alt="image" src="https://github.com/akfamily/aktools/assets/7601387/dda57774-9e5a-4b18-97db-729f069ba0bc">

**Comment by albertandking** [comment]
> Python 3.10.12 运行aktools 提示 No module named uvicorn，完整提示下图，这是怎么回事 <img alt="image" width="566" src="https://private-user-images.githubusercontent.com/7601387/313141708-dda57774-9e5a-4b18-97db-729f069ba0bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Mjk1MTQsIm5iZiI6MTcxMDkyOTIxNCwicGF0aCI6Ii83NjAxMzg3LzMxMzE0MTcwOC1kZGE1Nzc3NC05ZTVhLTRiMTgtOTdkYi03MjlmMDY5YmEwYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTAwNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZhZDFjYzg1ZmU4YjZjZGYyM2U4YTFhMWM2ODY0NTlmZTVkNmZmOTkyNGNlMmJmYzliYWE4ZTkzOGZjZWI3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xJVm3HFyirRIzQsZVWKEPlLQo-84ZewboJcOzdwrKwQ">

项目运行正常，应该是你那边本地环境的问题

**Comment by TreasureX000** [comment]
遇到了同样的问题，后来有解决吗
