### ISSUE TITLE
match_main_contract 调用报错

### ISSUE THREAD

**Issue by lalalalalaqaq** [akfamily/aktools#159]
1. 版本号 
当前的 AKTools 版本为：0.0.86，AKShare 版本为：1.12.95
2. 错误内容 
<img width="980" alt="image" src="https://github.com/akfamily/aktools/assets/77088455/524a7cd4-8798-4853-94e2-5761f62a185c">

3. 设备 ：
调用 macos 和linux 的aktool 都会产生这个问题

4. 现象  ： 
只要调用 host:port/api/public/match_main_contract, 返回的内容都是null ， 查aktools 的log就会有error打印

**Comment by albertandking** [comment]
> 4\. match_main_contract

该接返回的是 str，不能通过 http 调用

**Comment by lalalalalaqaq** [comment]
那正确打开的方式应该是怎样呢？我希望通过java调用akshare
