### ISSUE TITLE
Error: Got unexpected extra argument (Files\Python312\Lib\site-packages\aktools)

### ISSUE THREAD

**Issue by double2li** [akfamily/aktools#168]
python -m aktools
请访问：http://127.0.0.1:8080/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools
当前的 AKTools 版本为：0.0.86，AKShare 版本为：1.14.27
点击打开 HTTP API 主页：http://127.0.0.1:8080/
点击打开接口导览：http://127.0.0.1:8080/docs
Usage: python -m uvicorn [OPTIONS] APP
Try 'python -m uvicorn --help' for help.

Error: Got unexpected extra argument (Files\Python312\Lib\site-packages\aktools)

系统win10，python3.12

**Comment by albertandking** [comment]
> python -m aktools 请访问：http://127.0.0.1:8080/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools 当前的 AKTools 版本为：0.0.86，AKShare 版本为：1.14.27 点击打开 HTTP API 主页：http://127.0.0.1:8080/ 点击打开接口导览：http://127.0.0.1:8080/docs Usage: python -m uvicorn [OPTIONS] APP Try 'python -m uvicorn --help' for help.
> 
> Error: Got unexpected extra argument (Files\Python312\Lib\site-packages\aktools)
> 
> 系统win10，python3.12

按文档说明使用；目前测试是正常的
