### ISSUE TITLE
请问这是什么报错啊，python小白

### ISSUE THREAD

**Issue by li1287044700** [akfamily/aktools#169]
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      DEBUG:helpers.v8_build:Cloning depot tools
      DEBUG:helpers.v8_build:Calling: 'git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git' from working directory /tmp/pip-install-fhgehdzb/mini-racer_d9072aeed3a746b7a262dfc9936f5f74/v8_workspace
      Cloning into 'depot_tools'...
      fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Failed connect to chromium.googlesource.com:443; Connection timed out
      Traceback (most recent call last):
        File "/usr/local/python3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/python3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel

**Comment by albertandking** [comment]
> Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [31 lines of output] DEBUG:helpers.v8_build:Cloning depot tools DEBUG:helpers.v8_build:Calling: 'git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git' from working directory /tmp/pip-install-fhgehdzb/mini-racer_d9072aeed3a746b7a262dfc9936f5f74/v8_workspace Cloning into 'depot_tools'... fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Failed connect to chromium.googlesource.com:443; Connection timed out Traceback (most recent call last): File "/usr/local/python3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in main() File "/usr/local/python3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/python3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel

应该是 mini-racer  安装的问题，可以用国内的镜像试试
