### ISSUE TITLE
AKTools在使用AKSharer的会员持仓排名所有接口是返回全是异常

### ISSUE THREAD

**Issue by dahong38** [akfamily/aktools#174]
问题简述：
关于AKShare在使用AKTooks工具实现后，目前发现期货数据里关于“会员持仓排名”的全部接口（[https://akshare.akfamily.xyz/data/futures/futures.html#id30），](https://akshare.akfamily.xyz/data/futures/futures.html#id30%EF%BC%89%EF%BC%8C) 在使用AKTools中无法获取到数据，而且都是返回信息为：Invalid HTTP request received. 或Internal Server Error；但若是在Python环境下，直接引用AKShare通过这些接口取数是正常的。
注：目前使用AKShare及AKTools的版本每次都是升至最后的
上述问题测试的环境截图：
![ab97348a012e608475f3792c03af76d](https://github.com/user-attachments/assets/adae7918-ca15-4e43-a096-fbfc389182b5)
**以下是Postman测试结果：**
![858212404169d82fdd5eadad585b2f9](https://github.com/user-attachments/assets/783d912d-7597-4f9c-b230-95d20b89d451)
![image](https://github.com/user-attachments/assets/01f2607c-bbc5-4ce4-b8b4-e92cff56a6c8)

**目前发现发下接口都存在上述问题：**
get_cffex_rank_table
get_czce_rank_table
futures_dce_position_rank
get_shfe_rank_table
futures_gfex_position_rank

虽然说这些接口提供了pandas.DataFrame数据格式，但在AKTools里无法正常返回数据，这是不是异常，本人对Python并不太熟悉，不知这样是否正常。但本人的项目是通过第三方开发语言实现取用这些财经数据的，而AKTools工具本身实现就是如此的服务。所以，上述不能在AKTools工具后返回数据的接口，能否在后面的版本里实现数据的正常返回？感谢！

**Comment by albertandking** [comment]
> 问题简述： 关于AKShare在使用AKTooks工具实现后，目前发现期货数据里关于“会员持仓排名”的全部接口（[https://akshare.akfamily.xyz/data/futures/futures.html#id30），](https://akshare.akfamily.xyz/data/futures/futures.html#id30%EF%BC%89%EF%BC%8C) 在使用AKTools中无法获取到数据，而且都是返回信息为：Invalid HTTP request received. 或Internal Server Error；但若是在Python环境下，直接引用AKShare通过这些接口取数是正常的。 注：目前使用AKShare及AKTools的版本每次都是升至最后的 上述问题测试的环境截图： ![ab97348a012e608475f3792c03af76d](https://private-user-images.githubusercontent.com/129848366/384862144-adae7918-ca15-4e43-a096-fbfc389182b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTg0NTgsIm5iZiI6MTczMTMxODE1OCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0ODYyMTQ0LWFkYWU3OTE4LWNhMTUtNGU0My1hMDk2LWZiZmMzODkxODJiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwOTQyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDRjOTFiZGYxNjQ4Mjk4ZDg4Y2UyZjlmOWIxOWFhNGU0YTk4YTZkMGQ1NDNjYTQ4Yzc5NmZhMDM3MTAyYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YTUBD6puT95Q8ZVbGA5ZUJWniPBFB0rB7EU_2E_1dWE) **以下是Postman测试结果：** ![858212404169d82fdd5eadad585b2f9](https://private-user-images.githubusercontent.com/129848366/384588926-783d912d-7597-4f9c-b230-95d20b89d451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTg0NTgsIm5iZiI6MTczMTMxODE1OCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0NTg4OTI2LTc4M2Q5MTJkLTc1OTctNGY5Yy1iMjMwLTk1ZDIwYjg5ZDQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwOTQyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGZmZDgyZTg0YjdhZGQ0N2QxMGJjYTg5MzI1MDUzMDA4Nzk0OWJhZDNhY2E0NTZmNjI0ZmYyZjA2MzUzYjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rhh5zOaiWTJISORGJQXYvlR-xYdC_2mQ_kl5xyQw8mc) ![image](https://private-user-images.githubusercontent.com/129848366/384864846-01f2607c-bbc5-4ce4-b8b4-e92cff56a6c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTg0NTgsIm5iZiI6MTczMTMxODE1OCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0ODY0ODQ2LTAxZjI2MDdjLWJiYzUtNGNlNC1iOGI0LWU5MmNmZjU2YTZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwOTQyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWEzNTQ1NGU3NmVkMDJkZWM0ODEwNDY2ODc3ZGVkZjkyMzE4NWU0NzkyMmU4YjZiNWM2NjBjMjNmMGEzNTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bmV3zTWFJXhx45tNRbwU55cdmorrddnNBTJ_Gc7afqI)
> 
> **目前发现发下接口都存在上述问题：** get_cffex_rank_table get_czce_rank_table futures_dce_position_rank get_shfe_rank_table futures_gfex_position_rank
> 
> 虽然说这些接口提供了pandas.DataFrame数据格式，但在AKTools里无法正常返回数据，这是不是异常，本人对Python并不太熟悉，不知这样是否正常。但本人的项目是通过第三方开发语言实现取用这些财经数据的，而AKTools工具本身实现就是如此的服务。所以，上述不能在AKTools工具后返回数据的接口，能否在后面的版本里实现数据的正常返回？感谢！

会在后续中将 AKShare 相关接口的返回都统一到 pandas.DataFrame 格式后，利用 AKTools 就可以正常返回数据
