### ISSUE TITLE
服务器部分接口返回Internal Server Error 

### ISSUE THREAD

**Issue by lain1936** [akfamily/aktools#179]
主页和部分接口直接 Internal Server Error
fastapi 开启debug=True
发现这个抓取最新开源版本的报错，但是看网页是又有这个数据的
```
500 Server Error
AttributeError: 'NoneType' object has no attribute 'text'
Traceback

File /usr/local/lib/python3.10/dist-packages/aktools/utils.py, line 31, in get_latest_version‒

28.     soup = BeautifulSoup(r.text, "lxml")

29.     version = (

30.         soup.find("h1", attrs={"class": "package-header__name"})

31.         .text.strip()

32.         .split(" ")[1]

33.     )

34.     return version
```

**Comment by dahong38** [comment]
我也遇到同样的问题，请问解决了吗？

**Comment by lain1936** [comment]
> 我也遇到同样的问题，请问解决了吗？

我把Soup那里注释掉，直接返回个 字符串,  
比如
`return "0.88"`

接口就成功了，首页可以打开


不过获取东财和新浪会经常超时。

东财的我把对应函数的request 时间15秒改成更高也会超时
不超时大概2秒能获取

按理说和这里的问题不是同一个，应该没影响
不在你用实时数据遇到超时没

**Comment by dahong38** [comment]
我的连首页都打不开，直接显示Internal Server Error
接口请求时超时吗？不是可以设置请求超时时间吗？

**Comment by lain1936** [comment]
我感觉是ip限制，东财的5次刷新才能出结果
首页打不开

首页打不开的时候其实接口是可以访问的

我排错是
https://github.com/akfamily/aktools/blob/main/aktools/main.py#L34
加了 debug=True,网页调试模式， 打开主页找的错

```
app = FastAPI(
    title="欢迎访问 AKTools 为 AKShare 打造的 HTTP API 在线文档",
    description="AKTools 是 AKShare 的 HTTP API 工具, 主要目的是使 AKShare 的数据接口部署到服务器，从而让用户通过 HTTP 访问相关接口来获取所需要的数据",
    version=akshare.__version__,
    redoc_url=None,
    debug=True,
)
```

我是直接在 /usr/local/lib/python3.10/dist-packages/aktools
改对应文件的 （windows pip下载的包可能在其他路径）

报错的话就是首页就不报错了
https://github.com/akfamily/aktools/blob/main/aktools/utils.py#L34

```
@lru_cache()
def get_latest_version(package: str = "akshare") -> str:
    """
    获取开源库的最新版本
    https://pypi.org/project/akshare/
    :param package: 库名称
    :type package: str
    :return: 版本
    :rtype: str
   
    url = f"https://pypi.org/project/{package}"
    try:
        r = requests.get(url, verify=False)
    except requests.exceptions.ProxyError:
        return "0.0.0"
    soup = BeautifulSoup(r.text, "lxml")
    version = (
        soup.find("h1", attrs={"class": "package-header__name"})
        .text.strip()
        .split(" ")[1]
    )
    return version

    """
    return "0.0.88"
```

**Comment by albertandking** [comment]
> 主页和部分接口直接 Internal Server Error fastapi 开启debug=True 发现这个抓取最新开源版本的报错，但是看网页是又有这个数据的
> 
> ```
> 500 Server Error
> AttributeError: 'NoneType' object has no attribute 'text'
> Traceback
> 
> File /usr/local/lib/python3.10/dist-packages/aktools/utils.py, line 31, in get_latest_version‒
> 
> 28.     soup = BeautifulSoup(r.text, "lxml")
> 
> 29.     version = (
> 
> 30.         soup.find("h1", attrs={"class": "package-header__name"})
> 
> 31.         .text.strip()
> 
> 32.         .split(" ")[1]
> 
> 33.     )
> 
> 34.     return version
> ```

已修复，升级到 AKTools 0.0.89 使用，因为是 pypi 页面变化
