### ISSUE TITLE
AKTools能成功开启但请求全部出错（Internal Server Error）

### ISSUE THREAD

**Issue by dahong38** [akfamily/aktools#180]
当前使用Python 3.13.0，AKShare版本为1.15.44，AKTools版本为0.0.88，运行环境为64位的Windows 10 终端下执行：
**python -m aktools -P 9977  -- 执行结果如下（图片无法正常上传）：**
C:\Users\Administrator>python -m aktools -P 9977
请访问：http://127.0.0.1:9977/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools
当前的 AKTools 版本为：0.0.88，AKShare 版本为：1.15.44
点击打开 HTTP API 主页：http://127.0.0.1:9977/
点击打开接口导览：http://127.0.0.1:9977/docs
INFO:     Started server process [10940]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:9977 (Press CTRL+C to quit)

**将得到的主页地址在浏览器上打开，结果如下：**
浏览器url：http://127.0.0.1:9977/
500 Internal Server Error

**通过使用AKShare接口申请数据请求时，结果也差不多：**
![数据请求失败信息](https://github.com/user-attachments/assets/b7985315-a8a1-4594-b89c-48a416b8eff0)

**一直以来，通过上述方式使用AKTools架接使用AKShare接口获取财经数据都是正常的，这几天就出现上述问题，而且也更新各版本：**
pip install akshare --upgrade -i https://pypi.org/simple
pip install aktools --upgrade -i https://pypi.org/simple

**最后还是使用中出现上述问题，请问是我那边操作出现了什么问题，还是AKTools对AKShare最新版本支持出现了问题？感谢解决！**

**Comment by albertandking** [comment]
> 当前使用Python 3.13.0，AKShare版本为1.15.44，AKTools版本为0.0.88，运行环境为64位的Windows 10 终端下执行： **python -m aktools -P 9977 -- 执行结果如下（图片无法正常上传）：** C:\Users\Administrator>python -m aktools -P 9977 请访问：http://127.0.0.1:9977/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools 当前的 AKTools 版本为：0.0.88，AKShare 版本为：1.15.44 点击打开 HTTP API 主页：http://127.0.0.1:9977/ 点击打开接口导览：http://127.0.0.1:9977/docs INFO: Started server process [10940] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://127.0.0.1:9977 (Press CTRL+C to quit)
> 
> **将得到的主页地址在浏览器上打开，结果如下：** 浏览器url：http://127.0.0.1:9977/ 500 Internal Server Error
> 
> **通过使用AKShare接口申请数据请求时，结果也差不多：** ![数据请求失败信息](https://private-user-images.githubusercontent.com/129848366/394999199-b7985315-a8a1-4594-b89c-48a416b8eff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTkzNTEsIm5iZiI6MTczMzk5OTA1MSwicGF0aCI6Ii8xMjk4NDgzNjYvMzk0OTk5MTk5LWI3OTg1MzE1LWE4YTEtNDU5NC1iODljLTQ4YTQxNmI4ZWZmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxMDI0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2FjMDIxY2YwNWM4NjJkOGM5MWMzNjFiY2RkOTkzMWNhMmU1NjI5ZDBmYjE1ZWQyNmYwYmI5ZGFiOTI0NjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WH3SAK_Mtq0N7o3z0wVjhMmzhMzr1LSV_6s0f4c1MxY)
> 
> **一直以来，通过上述方式使用AKTools架接使用AKShare接口获取财经数据都是正常的，这几天就出现上述问题，而且也更新各版本：** pip install akshare --upgrade -i https://pypi.org/simple pip install aktools --upgrade -i https://pypi.org/simple
> 
> **最后还是使用中出现上述问题，请问是我那边操作出现了什么问题，还是AKTools对AKShare最新版本支持出现了问题？感谢解决！**

已修复，升级到 AKTools 0.0.89 使用，因为是 pypi 页面变化

**Comment by dahong38** [comment]
好的，已升级，解决了，感谢！
