### ISSUE TITLE
How to change the port number to another port instead of the default port 8080?

### ISSUE THREAD

**Issue by YuanYuanDeLiShu** [akfamily/aktools#45]
![image](https://user-images.githubusercontent.com/37896945/156101089-307543c9-6b5b-4098-b8ac-1c46cce5c7d4.png)
How to change the port number to another port instead of the default port 8080?

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/37896945/156101089-307543c9-6b5b-4098-b8ac-1c46cce5c7d4.png) How to change the port number to another port instead of the default port 8080?

可以通过：`python -m aktools --host 0.0.0.0 --port 8888` 来修改 host 和 port，详情可以访问文档
