### ISSUE TITLE
docker部署后，解析域名访问报错

### ISSUE THREAD

**Issue by fzlinjianhui** [akfamily/aktools#47]
No supported WebSocket library detected. Please use 'pip install uvicorn[standard]', or install 'websockets' or 'wsproto' manually.

用ip:端口可以正常使用
这是为啥呢
ps：我解析了一个https来访问的

**Comment by jindaxiang** [comment]
> No supported WebSocket library detected. Please use 'pip install uvicorn[standard]', or install 'websockets' or 'wsproto' manually.
> 
> 用ip:端口可以正常使用 这是为啥呢 ps：我解析了一个https来访问的

用 http 访问，https 协议没有证书

**Comment by fzlinjianhui** [comment]
> > No supported WebSocket library detected. Please use 'pip install uvicorn[standard]', or install 'websockets' or 'wsproto' manually.
> > 用ip:端口可以正常使用 这是为啥呢 ps：我解析了一个https来访问的
> 
> 用 http 访问，https 协议没有证书

那请问这个跨域问题如何处理？
