### ISSUE TITLE
返回服务器详细错误代码

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/aktools#50]
接口：stock_gdfx_free_top_10_em
读取sz000420 （吉林化纤）2022-3-31的十大流通股东，返回错误：
![image](https://user-images.githubusercontent.com/13130628/169206315-39d89f21-c84f-4008-96c6-c3af706df26f.png)

在cmd窗口里显示的错误为：
![image](https://user-images.githubusercontent.com/13130628/169205945-ad960ac8-cf6a-448d-ae6e-caa8b5874b25.png)

希望返回Http错误时，能返回这行：ValueError: Length mismatch: Expected axis has 1 elements, new values have 12 elements。
以便可以根据具体的原因选择代码执行路径。

**Comment by jindaxiang** [comment]
> sz000420

是个好注意，后续会把异常暴露出来
