### ISSUE TITLE
windows7 系统启动失败

### ISSUE THREAD

**Issue by xsstomy** [akfamily/aktools#60]
先感谢提供免费的库。

windows 7
python 3.8.6

安装最新版本 0.0.60 

执行

`python -m aktools`

报以下错误

Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.
Error: Got unexpected extra argument (Files\python\lib\site-packages\aktools)

**Comment by jindaxiang** [comment]
> 先感谢提供免费的库。
> 
> windows 7 python 3.8.6
> 
> 安装最新版本 0.0.60
> 
> 执行
> 
> `python -m aktools`
> 
> 报以下错误
> 
> Usage: uvicorn [OPTIONS] APP Try 'uvicorn --help' for help. Error: Got unexpected extra argument (Files\python\lib\site-packages\aktools)

可以看看环境是否配置好，建设升级到 Windows 10 及以上版本
