### ISSUE TITLE
报错：PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/aktools#73]
Aktools：0.0.67
python:3.10.5
anaconda3:2022.05 -64
os:windows 10
网上搜索了多种方法常识，依然报错
1. 以管理员方式运行
2. 修改文件夹只读
3. 从C盘安装到D盘
之前的版本正常
![image](https://user-images.githubusercontent.com/13130628/173178309-3fec92fc-fd10-40ae-82b3-0983b809ed53.png)

**Comment by Cuiqs76** [comment]
换了一台电脑升级后，还是同样的问题：
(base) PS C:\Users\cuiqs> pip install akshare  --upgrade
Requirement already satisfied: akshare in d:\users\cuiqs\anaconda3\lib\site-packages (1.5.96)
Collecting akshare
  Downloading akshare-1.6.15-py3-none-any.whl (918 kB)
     |████████████████████████████████| 918 kB 30 kB/s
Requirement already satisfied: jsonpath>=0.82 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (0.82)
Requirement already satisfied: xlrd>=1.2.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (2.0.1)
Requirement already satisfied: urllib3>=1.25.8 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (1.26.7)
Requirement already satisfied: pandas>=0.25 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (1.3.4)
Requirement already satisfied: requests>=2.22.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (2.26.0)
Requirement already satisfied: decorator>=4.4.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (5.1.0)
Requirement already satisfied: py-mini-racer>=0.6.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (0.6.0)
Requirement already satisfied: lxml>=4.2.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (4.6.3)
Requirement already satisfied: pypinyin>=0.35.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (0.46.0)
Requirement already satisfied: tqdm>=4.43.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (4.62.3)
Requirement already satisfied: tabulate>=0.8.6 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (0.8.9)
Requirement already satisfied: beautifulsoup4>=4.9.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (4.10.0)
Requirement already satisfied: requests-cache>=0.9.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (0.9.4)
Requirement already satisfied: openpyxl>=3.0.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (3.0.9)
Requirement already satisfied: html5lib>=1.0.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (1.1)
Requirement already satisfied: websocket-client>=0.56.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare) (1.3.2)
Requirement already satisfied: soupsieve>1.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from beautifulsoup4>=4.9.1->akshare) (2.2.1)
Requirement already satisfied: webencodings in d:\users\cuiqs\anaconda3\lib\site-packages (from html5lib>=1.0.1->akshare) (0.5.1)
Requirement already satisfied: six>=1.9 in d:\users\cuiqs\anaconda3\lib\site-packages (from html5lib>=1.0.1->akshare) (1.16.0)
Requirement already satisfied: et-xmlfile in d:\users\cuiqs\anaconda3\lib\site-packages (from openpyxl>=3.0.3->akshare) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from pandas>=0.25->akshare) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from pandas>=0.25->akshare) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from pandas>=0.25->akshare) (1.20.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests>=2.22.0->akshare) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests>=2.22.0->akshare) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests>=2.22.0->akshare) (3.2)
Requirement already satisfied: cattrs<2.0,>=1.8 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.10.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.4.4)
Requirement already satisfied: attrs<22.0,>=21.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (21.2.0)
Requirement already satisfied: url-normalize<2.0,>=1.4 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.4.3)
Requirement already satisfied: colorama in d:\users\cuiqs\anaconda3\lib\site-packages (from tqdm>=4.43.0->akshare) (0.4.4)
Installing collected packages: akshare
  Attempting uninstall: akshare
    Found existing installation: akshare 1.5.96
    Uninstalling akshare-1.5.96:
      Successfully uninstalled akshare-1.5.96
Successfully installed akshare-1.6.15
(base) PS C:\Users\cuiqs> pip install aktools  --upgrade
Requirement already satisfied: aktools in d:\users\cuiqs\anaconda3\lib\site-packages (0.0.51)
Collecting aktools
  Downloading aktools-0.0.67-py3-none-any.whl (17 kB)
Requirement already satisfied: fastapi>=0.70.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from aktools) (0.76.0)
Requirement already satisfied: akshare>=1.4.95 in d:\users\cuiqs\anaconda3\lib\site-packages (from aktools) (1.6.15)
Collecting jinja2>=3.1.2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 386 kB/s
Requirement already satisfied: uvicorn>=0.16.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from aktools) (0.17.6)
Requirement already satisfied: python-multipart>=0.0.5 in d:\users\cuiqs\anaconda3\lib\site-packages (from aktools) (0.0.5)
Requirement already satisfied: pypinyin>=0.35.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (0.46.0)
Requirement already satisfied: pandas>=0.25 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (1.3.4)
Requirement already satisfied: decorator>=4.4.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (5.1.0)
Requirement already satisfied: urllib3>=1.25.8 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (1.26.7)
Requirement already satisfied: lxml>=4.2.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (4.6.3)
Requirement already satisfied: requests-cache>=0.9.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (0.9.4)
Requirement already satisfied: jsonpath>=0.82 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (0.82)
Requirement already satisfied: tqdm>=4.43.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (4.62.3)
Requirement already satisfied: websocket-client>=0.56.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (1.3.2)
Requirement already satisfied: xlrd>=1.2.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (2.0.1)
Requirement already satisfied: tabulate>=0.8.6 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (0.8.9)
Requirement already satisfied: beautifulsoup4>=4.9.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (4.10.0)
Requirement already satisfied: openpyxl>=3.0.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (3.0.9)
Requirement already satisfied: py-mini-racer>=0.6.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (0.6.0)
Requirement already satisfied: html5lib>=1.0.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (1.1)
Requirement already satisfied: requests>=2.22.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from akshare>=1.4.95->aktools) (2.26.0)
Requirement already satisfied: soupsieve>1.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from beautifulsoup4>=4.9.1->akshare>=1.4.95->aktools) (2.2.1)
Requirement already satisfied: starlette==0.18.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from fastapi>=0.70.0->aktools) (0.18.0)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from fastapi>=0.70.0->aktools) (1.9.0)
Requirement already satisfied: typing-extensions in d:\users\cuiqs\anaconda3\lib\site-packages (from starlette==0.18.0->fastapi>=0.70.0->aktools) (3.10.0.2)
Requirement already satisfied: anyio<4,>=3.0.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from starlette==0.18.0->fastapi>=0.70.0->aktools) (3.5.0)
Requirement already satisfied: idna>=2.8 in d:\users\cuiqs\anaconda3\lib\site-packages (from anyio<4,>=3.0.0->starlette==0.18.0->fastapi>=0.70.0->aktools) (3.2)
Requirement already satisfied: sniffio>=1.1 in d:\users\cuiqs\anaconda3\lib\site-packages (from anyio<4,>=3.0.0->starlette==0.18.0->fastapi>=0.70.0->aktools) (1.2.0)
Requirement already satisfied: six>=1.9 in d:\users\cuiqs\anaconda3\lib\site-packages (from html5lib>=1.0.1->akshare>=1.4.95->aktools) (1.16.0)
Requirement already satisfied: webencodings in d:\users\cuiqs\anaconda3\lib\site-packages (from html5lib>=1.0.1->akshare>=1.4.95->aktools) (0.5.1)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp39-cp39-win_amd64.whl (17 kB)
Requirement already satisfied: et-xmlfile in d:\users\cuiqs\anaconda3\lib\site-packages (from openpyxl>=3.0.3->akshare>=1.4.95->aktools) (1.1.0)
Requirement already satisfied: pytz>=2017.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from pandas>=0.25->akshare>=1.4.95->aktools) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from pandas>=0.25->akshare>=1.4.95->aktools) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\users\cuiqs\anaconda3\lib\site-packages (from pandas>=0.25->akshare>=1.4.95->aktools) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests>=2.22.0->akshare>=1.4.95->aktools) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests>=2.22.0->akshare>=1.4.95->aktools) (2.0.4)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare>=1.4.95->aktools) (1.4.4)
Requirement already satisfied: url-normalize<2.0,>=1.4 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare>=1.4.95->aktools) (1.4.3)
Requirement already satisfied: attrs<22.0,>=21.2 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare>=1.4.95->aktools) (21.2.0)
Requirement already satisfied: cattrs<2.0,>=1.8 in d:\users\cuiqs\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare>=1.4.95->aktools) (1.10.0)
Requirement already satisfied: colorama in d:\users\cuiqs\anaconda3\lib\site-packages (from tqdm>=4.43.0->akshare>=1.4.95->aktools) (0.4.4)
Requirement already satisfied: click>=7.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from uvicorn>=0.16.0->aktools) (8.0.3)
Requirement already satisfied: h11>=0.8 in d:\users\cuiqs\anaconda3\lib\site-packages (from uvicorn>=0.16.0->aktools) (0.13.0)
Requirement already satisfied: asgiref>=3.4.0 in d:\users\cuiqs\anaconda3\lib\site-packages (from uvicorn>=0.16.0->aktools) (3.5.1)
Installing collected packages: MarkupSafe, jinja2, aktools
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Uninstalling MarkupSafe-1.1.1:
      Successfully uninstalled MarkupSafe-1.1.1
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.11.3
    Uninstalling Jinja2-2.11.3:
      Successfully uninstalled Jinja2-2.11.3
  Attempting uninstall: aktools
    Found existing installation: aktools 0.0.51
    Uninstalling aktools-0.0.51:
      Successfully uninstalled aktools-0.0.51
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-project 0.10.1 requires ruamel-yaml, which is not installed.
cookiecutter 1.7.2 requires Jinja2<3.0.0, but you have jinja2 3.1.2 which is incompatible.
cookiecutter 1.7.2 requires MarkupSafe<2.0.0, but you have markupsafe 2.1.1 which is incompatible.
Successfully installed MarkupSafe-2.1.1 aktools-0.0.67 jinja2-3.1.2
(base) PS C:\Users\cuiqs> python -m aktools
点击打开接口导览：http://127.0.0.1:8080/docs
Traceback (most recent call last):
  File "d:\Users\cuiqs\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\Users\cuiqs\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\Users\cuiqs\anaconda3\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\main.py", line 437, in main
    run(app, **kwargs)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "d:\Users\cuiqs\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "d:\Users\cuiqs\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "d:\Users\cuiqs\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\aktools\run.py", line 12, in <module>
    from core import app_core
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\aktools\core\__init__.py", line 3, in <module>
    from .api import app_core
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\aktools\core\api.py", line 155, in <module>
    short_path = get_template_path()
  File "d:\Users\cuiqs\anaconda3\lib\site-packages\aktools\datasets.py", line 20, in get_template_path
    with resources.path("aktools.assets", "html") as f:
  File "d:\Users\cuiqs\anaconda3\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "d:\Users\cuiqs\anaconda3\lib\importlib\resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
PermissionError: [Errno 13] Permission denied: 'd:\\Users\\cuiqs\\anaconda3\\lib\\site-packages\\aktools\\assets\\html'
(base) PS C:\Users\cuiqs>

**Comment by jindaxiang** [comment]
> Aktools：0.0.67 python:3.10.5 anaconda3:2022.05 -64 os:windows 10 网上搜索了多种方法常识，依然报错
> 
> 1. 以管理员方式运行
> 2. 修改文件夹只读
> 3. 从C盘安装到D盘
>    之前的版本正常
>    ![image](https://user-images.githubusercontent.com/13130628/173178309-3fec92fc-fd10-40ae-82b3-0983b809ed53.png)

感谢反馈问题，尝试用管理员开启 cmd 命令窗口，再运行相关的命令

**Comment by fker1115** [comment]
请问楼主解决了这个问题没有

**Comment by jindaxiang** [comment]
> > Aktools：0.0.67 python:3.10.5 anaconda3:2022.05 -64 os:windows 10 网上搜索了多种方法常识，依然报错
> > 
> > 1. 以管理员方式运行
> > 2. 修改文件夹只读
> > 3. 从C盘安装到D盘
> >    之前的版本正常
> >    ![image](https://user-images.githubusercontent.com/13130628/173178309-3fec92fc-fd10-40ae-82b3-0983b809ed53.png)
> 
> 感谢反馈问题，尝试用管理员开启 cmd 命令窗口，再运行相关的命令

已修复路径问题；升级到 AKTools 0.0.69 版本再试下看

**Comment by jindaxiang** [comment]
> 请问楼主解决了这个问题没有

已修复路径问题；升级到 AKTools 0.0.69 版本再试下看
