### ISSUE TITLE
希望热心人能给出更详尽的具体使用文档

### ISSUE THREAD

**Issue by kuramant** [akfamily/aktools#74]
感谢作者的无私奉献，我已经装好并能运行，限于能力有限看了文档后仍然不知道具体如何使用，希望能给出一个完整的示例，非常感谢！

**Comment by jindaxiang** [comment]
> 感谢作者的无私奉献，我已经装好并能运行，限于能力有限看了文档后仍然不知道具体如何使用，希望能给出一个完整的示例，非常感谢！

文档已经提供详细的说明指导
