### ISSUE TITLE
LPR数据没有返回日期字段

### ISSUE THREAD

**Issue by surjur** [akfamily/aktools#76]
aktools安装和运行指令：
docker run -di -p 8080:8080 registry.cn-shanghai.aliyuncs.com/akfamily/aktools:1.3.93 python -m aktools
docker run -p 8080:8080 registry.cn-shanghai.aliyuncs.com/akfamily/aktools:1.3.93 python -m aktools --host 0.0.0.0 --port 8080
访问LPR返回数据：
![image](https://user-images.githubusercontent.com/7477889/181916656-4e1fa0a5-3555-4653-9ace-656cde5d5258.png)
文档是有日期字段：
![image](https://user-images.githubusercontent.com/7477889/181916733-80a3d3bd-e11a-4a1f-a0ab-84e660d5cd24.png)
文档地址：https://www.akshare.xyz/data/macro/macro.html?highlight=lpr#lpr
是版本不对还是啥情况？
理论上按照文档意思我安装的应该是最新的吧
![image](https://user-images.githubusercontent.com/7477889/182006079-0db0cf7e-c4d5-4777-8531-a375f2af5fa4.png)

**Comment by surjur** [comment]
更新到akshare1.6.72有日期字段了

**Comment by surjur** [comment]
但是参数说明哪里看，比如倒序获取数据 
@jindaxiang

**Comment by surjur** [comment]
@jindaxiang 参数说明哪里看，比如倒序获取数据

**Comment by jindaxiang** [comment]
> @jindaxiang 参数说明哪里看，比如倒序获取数据

需要获取数据到本地后自行排序
