### ISSUE TITLE
PermissionError: [Errno 13] Permission denied 问题

### ISSUE THREAD

**Issue by fker1115** [akfamily/aktools#77]
作者您好。我用的anaconda环境，添加了系统变量直接在cmd或powershell里按操作执行。
运行错误，如下，这是什么原因呢？
C:\Users\Administrator>python -m aktools
点击打开接口导览：http://127.0.0.1:8080/docs
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 197, in _run_module
_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\anaconda3\Scripts\uvicorn.exe\__main__.py", line
7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line
1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line
1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line
1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line
754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", lin
e 407, in main
    run(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", lin
e 575, in run
    server.run()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", l
ine 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\anaconda3\lib\asyncio\runners.py", line 44, in ru
n
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 647,
in run_until_complete
    return future.result()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", l
ine 67, in serve
    config.load()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\config.py", l
ine 479, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\importer.py",
 line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Administrator\anaconda3\lib\importlib\__init__.py", line 127, i
n import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\run.py", line
 12, in <module>
    from core import app_core
  File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\core\__init__
.py", line 3, in <module>
    from .api import app_core
  File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\core\api.py",
 line 155, in <module>
    short_path = get_template_path()
  File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\datasets.py",
 line 20, in get_template_path
    with resources.path("aktools.assets", "html") as f:
  File "C:\Users\Administrator\anaconda3\lib\contextlib.py", line 119, in __ente
r__
    return next(self.gen)
  File "C:\Users\Administrator\anaconda3\lib\importlib\resources.py", line 175,
in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\anacon
da3\\lib\\site-packages\\aktools\\assets\\html'

**Comment by jindaxiang** [comment]
> 作者您好。我用的anaconda环境，添加了系统变量直接在cmd或powershell里按操作执行。 运行错误，如下，这是什么原因呢？ C:\Users\Administrator>python -m aktools 点击打开接口导览：http://127.0.0.1:8080/docs Traceback (most recent call last): File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 197, in _run_module _as_main return _run_code(code, main_globals, None, File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\anaconda3\Scripts\uvicorn.exe__main__.py", line 7, in sys.exit(main()) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 1128, in **call** return self.main(*args, **kwargs) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 1053, in main rv = self.invoke(ctx) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 754, in invoke return __callback(*args, **kwargs) File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", lin e 407, in main run( File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", lin e 575, in run server.run() File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", l ine 60, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\anaconda3\lib\asyncio\runners.py", line 44, in ru n return loop.run_until_complete(main) File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete return future.result() File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", l ine 67, in serve config.load() File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\config.py", l ine 479, in load self.loaded_app = import_from_string(self.app) File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string module = importlib.import_module(module_str) File "C:\Users\Administrator\anaconda3\lib\importlib__init__.py", line 127, i n import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\run.py", line 12, in from core import app_core File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\core__init__ .py", line 3, in from .api import app_core File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\core\api.py", line 155, in short_path = get_template_path() File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\datasets.py", line 20, in get_template_path with resources.path("aktools.assets", "html") as f: File "C:\Users\Administrator\anaconda3\lib\contextlib.py", line 119, in **ente r** return next(self.gen) File "C:\Users\Administrator\anaconda3\lib\importlib\resources.py", line 175, in _path_from_reader opener_reader = reader.open_resource(norm_resource) File "", line 1055, in open_resource PermissionError: [Errno 13] Permission denied: 'C:\Users\Administrator\anacon da3\lib\site-packages\aktools\assets\html'

需要以管理员的权限运行，可以在打开 cmd 窗口右键单击以管理员身份运行即可

**Comment by fker1115** [comment]
您好，问题还是存在啊。。。本来就用的管理员权限，换了一台电脑还是这个情况

**Comment by jindaxiang** [comment]
> > 作者您好。我用的anaconda环境，添加了系统变量直接在cmd或powershell里按操作执行。 运行错误，如下，这是什么原因呢？ C:\Users\Administrator>python -m aktools 点击打开接口导览：http://127.0.0.1:8080/docs Traceback (most recent call last): File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 197, in _run_module _as_main return _run_code(code, main_globals, None, File "C:\Users\Administrator\anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\anaconda3\Scripts\uvicorn.exe__main__.py", line 7, in sys.exit(main()) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 1128, in **call** return self.main(*args, **kwargs) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 1053, in main rv = self.invoke(ctx) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\Users\Administrator\anaconda3\lib\site-packages\click\core.py", line 754, in invoke return **callback(*args, **kwargs) File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", lin e 407, in main run( File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\main.py", lin e 575, in run server.run() File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", l ine 60, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\anaconda3\lib\asyncio\runners.py", line 44, in ru n return loop.run_until_complete(main) File "C:\Users\Administrator\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete return future.result() File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\server.py", l ine 67, in serve config.load() File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\config.py", l ine 479, in load self.loaded_app = import_from_string(self.app) File "C:\Users\Administrator\anaconda3\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string module = importlib.import_module(module_str) File "C:\Users\Administrator\anaconda3\lib\importlib__init**.py", line 127, i n import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\run.py", line 12, in from core import app_core File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\core__init__ .py", line 3, in from .api import app_core File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\core\api.py", line 155, in short_path = get_template_path() File "C:\Users\Administrator\anaconda3\lib\site-packages\aktools\datasets.py", line 20, in get_template_path with resources.path("aktools.assets", "html") as f: File "C:\Users\Administrator\anaconda3\lib\contextlib.py", line 119, in **ente r** return next(self.gen) File "C:\Users\Administrator\anaconda3\lib\importlib\resources.py", line 175, in _path_from_reader opener_reader = reader.open_resource(norm_resource) File "", line 1055, in open_resource PermissionError: [Errno 13] Permission denied: 'C:\Users\Administrator\anacon da3\lib\site-packages\aktools\assets\html'
> 
> 需要以管理员的权限运行，可以在打开 cmd 窗口右键单击以管理员身份运行即可

已修复路径问题；升级到 AKTools 0.0.69 版本再试下看

**Comment by jindaxiang** [comment]
> 您好，问题还是存在啊。。。本来就用的管理员权限，换了一台电脑还是这个情况

已修复路径问题；升级到 AKTools 0.0.69 版本再试下看
