### ISSUE TITLE
如何部署在云主机

### ISSUE THREAD

**Issue by fker1115** [akfamily/aktools#83]
感谢作者修复，最新的版本终于可以运行了。另外一个问题，我再我的腾讯云上运行这个服务，本地电脑用服务器ip无法访问，这个权限哪里可以开启？

**Comment by jindaxiang** [comment]
> 感谢作者修复，最新的版本终于可以运行了。另外一个问题，我再我的腾讯云上运行这个服务，本地电脑用服务器ip无法访问，这个权限哪里可以开启？

要在腾讯云开启对应的端口
