### ISSUE TITLE
访问创新高接口  stock_rank_cxg_ths  提示失败，stock_rank_cxg_ths?symbol="半年新高"

### ISSUE THREAD

**Issue by xsstomy** [akfamily/aktools#84]
![image](https://user-images.githubusercontent.com/8943787/189051748-4d759fb8-6769-4f83-bee9-ad114cb36e46.png)

**Comment by xsstomy** [comment]
直接访问 接口是可以获取到数据  public/stock_rank_cxg_ths

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/8943787/189051748-4d759fb8-6769-4f83-bee9-ad114cb36e46.png)

带参数访问，请参照：**http://localhost:8080/api/public/stock_rank_cxg_ths?symbol=%E5%8D%8A%E5%B9%B4%E6%96%B0%E9%AB%98**
