### ISSUE TITLE
给返回的json带上index，像stock_us_daily这样的接口没有date数据，因为date在pd中是index

### ISSUE THREAD

**Issue by zxy177280210** [akfamily/aktools#89]
给返回的json带上index，像stock_us_daily这样的接口没有date数据，因为date在pd中是index

**Comment by jindaxiang** [comment]
> 

是的，后续的接口设计及修复已经没有使用 index，相关接口会尽快修复

**Comment by jindaxiang** [comment]
> 给返回的json带上index，像stock_us_daily这样的接口没有date数据，因为date在pd中是index

stock_us_daily 已经修复，升级到 AKShare 1.7.29 版本使用
